artifacts_root: artifacts


Data_extraction:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/stock_data.csv
  

Data_Transformation:
  root_dir: artifacts/transformation
  transformed_data_file: artifacts/transformation/processed_stock_data.csv


Model_Training:
  root_dir: artifacts/model_training
  trained_model_dir: artifacts/model_training/models
  scaler_dir: artifacts/model_training/scalers
  transformed_data_file: artifacts/transformation/processed_stock_data.csv

Prediction:
  root_dir: artifacts/predictions
  forecast_file: artifacts/predictions/forecast.csv