artifacts_root: artifacts


Data_extraction:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/stock_data.csv
  

Data_Transformation:
  root_dir: artifacts/transformation
  transformed_data_file: artifacts/transformation/processed_stock_data.csv

Data_Loading:
  DB_HOST: database-1.c5wq2iw6459n.eu-north-1.rds.amazonaws.com
  DB_PORT: 5432
  DB_NAME: MarketETL
  DB_USER: postgres
  DB_PASSWORD: ProjectPassword
  SSL_ROOT_CERT: global-bundle.pem